Repository modooSugangOrg/modooSugang_FE, pull requests merged in 2022-04, with the labels that each got.

#28 [✨ feature] 관리자 자료조회 페이지 구현
  src/components/Manage_Search.js
  src/components/assets/Search.js
  src/components/views/ManagerSearchLogBox.js
  src/components/views/SearchLogTable.js
  src/components/views/StudentEnrollmentpageBox.js
Labels: ✨ Feature

#40 [구현] 수강신청 페이지 장바구니 신청목록 테이블 추가
  src/components/views/BasketTable.js
  src/components/views/StudentEnrollmentpageBox.js
Labels: ✨ Feature

#42 [♻️ Refactor] 테이블 상단바 조정 & 안쓰는 코드 정리
  src/components/views/BucketEnrollmentTable.js
  src/components/views/BucketTable.js
  src/components/views/ClassSearchTable.js
  src/components/views/EnrolledTable.js
  src/components/views/EnrollmentTable.js
  src/components/views/ManagerTimeTable.js
  src/components/views/MypageResultTable.js
  src/components/views/SearchLogTable.js
  src/components/views/StudentEnrollmentpageBox.js
  src/components/views/TimeTable2.js
Labels: ♻️ Refactor

#44 AppFooter 추가
  package-lock.json
  src/components/Manage_Period.js
  src/components/Manage_Search.js
  src/components/Manage_UploadStudent.js
  src/components/Manage_UploadTimeTable.js
  src/components/Student_Bucket.js
  src/components/Student_Class.js
  src/components/Student_Enrollmentpage.js
  src/components/Student_Mypage.js
  src/components/views/AppFooter.js
Labels: ♻️ Refactor

#46 [feature] Springboot 연결을 위한 Axios 설정
  package-lock.json
  package.json
  src/App.js
  src/apiAxios.js
  src/components/Testpage.js
Labels: ✨ Feature

#47 [ Feature/login ] 로그인 페이지 개선 + api 요청
  src/apiAxios.js
  src/components/Homepage.js
  src/components/SignIn.js
  src/components/views/StudentMainpageBox.js
Labels: ✨ Feature

#53 [✨ feature] 학생페이지 - 교과목 페이지 기능 구현
  src/components/SignIn.js
  src/components/assets/FileUploadButton.js
  src/components/views/ClassSearch.js
  src/components/views/ClassSearchTable.js
  src/components/views/ManagerSearchLogBox.js
  src/components/views/StudentMainpageBox.js
Labels: ✨ Feature

#58 Refactor/adjust between pages
  src/App.js
  src/components/SignIn.js
  src/components/assets/FileUploadButton.js
  src/components/assets/Search.js
  src/components/views/ClassSearch.js
  src/components/views/ClassSearchTable.js
  src/components/views/ManagerSearchLogBox.js
  src/components/views/ManagerTimetableBox.js
  src/components/views/SearchLogTable.js
  src/components/views/StudentMainpageBox.js
  src/components/views/TimetableBox2.js
Labels: ♻️ Refactor, ✨ Feature

#61 [✨ feature] 마이페이지 기능 구현
  package-lock.json
  package.json
  src/components/Student_Mypage.js
  src/components/views/MypageResultTable.js
  src/components/views/StudentMypageLayout.js
  src/components/views/StudentMypageTimetable.js
  src/components/views/Student_Mypage_Table1.js
Labels: ✨ Feature

#66 [:ambulance: hotfix] nginx.conf 파일 문법 수정
  nginx.conf
Labels: 🚑️ Hotfix
